config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resource :active_shipping_settings, only: [:show, :update, :edit]

    resources :products, only: [] do
      resources :product_packages
    end
  end
end

app/models/spree/product_package.rb
module Spree
  class ProductPackage < ActiveRecord::Base
    belongs_to :product

    validates :length, :width, :height, :weight,
              numericality: { only_integer: true,
                                message: Spree.t('validation.must_be_int'),
                                greater_than: 0 }
  end
end

app/controllers/spree/admin/product_packages_controller.rb
module Spree
  module Admin
    class ProductPackagesController < ResourceController
      belongs_to 'spree/product', find_by: :slug
      before_action :load_data

      private
        def load_data
          @product = Product.find_by(slug: params[:product_id])
        end

        def permitted_product_package_attributes
          [:length, :width, :height, :weight]
        end
    end
  end
end

app/views/spree/admin/product_packages/_form.html.erb
<div class="row" data-hook="admin_product_package_form_fields">
  <div class="col-md-6">
    <div data-hook="length" class="field">
      <%= f.label Spree.t(:length) %><br>
      <%= f.text_field :length, class: "form-control" %>
    </div>
    <div data-hook="width" class="field">
      <%= f.label Spree.t(:width) %><br>
      <%= f.text_field :width, class: "form-control" %>
    </div>
  </div>
  <div class="col-md-6">
    <div data-hook="height" class="field">
      <%= f.label Spree.t(:height) %><br>
      <%= f.text_field :height, class: "form-control" %>
    </div>
    <div data-hook="weight" class="field">
      <%= f.label Spree.t(:weight) %><br>
      <%= f.text_field :weight, class: "form-control" %>
    </div>
  </div>
</div>

app/views/spree/admin/product_packages/edit.html.erb
<%= form_for [:admin, @product, @product_package], html: { multipart: true } do |f| %>
  <fieldset data-hook="edit_product_package">
    <legend align="center"><%= Spree.t(:edit_package) %></legend>

      <%= render partial: 'form', locals: { f: f } %>

      <%= render partial: 'spree/admin/shared/edit_resource_links', locals: { collection_url: admin_product_product_packages_url(@product) } %>
  </fieldset>
<% end %>

<%= javascript_include_tag 'admin/product_packages/edit.js' %>

app/views/spree/admin/product_packages/index.html.erb
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_package), new_admin_product_product_package_url(@product), { class: "btn-success", icon: 'add', id: 'new_product_package_link' } %>
<% end %>

<% content_for :head do %>
  <%= javascript_include_tag 'admin/product_packages/index.js' %>
<% end %>

<%= render partial: 'spree/admin/shared/sub_menu/product' %>
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: 'Product Packages' } %>

<div id="product_packages" data-hook></div>

<% unless @product.reload.product_packages.any? %>
  <div class="no-objects-found">
    <%= Spree.t(:no_packages_found) %>.
  </div>
<% else %>
  <table class="table">
    <thead data-hook="option_header">
      <tr data-hook="product_packages_header">
        <th><%= Spree.t(:length) %></th>
        <th><%= Spree.t(:width) %></th>
        <th><%= Spree.t(:height) %></th>
        <th><%= Spree.t(:weight) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody id="product_packages" data-hook>
      <% @product.product_packages.each do |package| %>
        <tr id="<%= dom_id(package) %>" data-hook="product_package_row">
          <td><%= package.length %></td>
          <td><%= package.width %></td>
          <td><%= package.height %></td>
          <td><%= package.weight %></td>
          <td class="actions actions-2 text-right">
            <%= link_to_edit(package, no_text: true) %>
            <%= link_to_delete(package, no_text: true) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/product_packages/new.html.erb
<%= form_for [:admin, @product, @product_package], html: { multipart: true } do |f| %>
  <fieldset data-hook="new_product_package">
    <legend align="center"><%= Spree.t(:new_package) %></legend>

      <%= render partial: 'form', locals: { f: f } %>

      <%= render partial: 'spree/admin/shared/edit_resource_links', locals: { collection_url: admin_product_product_packages_url(@product) } %>
  </fieldset>
<% end %>

<%= javascript_include_tag 'admin/product_packages/new.js' %>