config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resource :active_shipping_settings, only: [:show, :update, :edit]

    resources :products, only: [] do
      resources :product_packages
    end
  end
end

app/controllers/spree/admin/active_shipping_settings_controller.rb
class Spree::Admin::ActiveShippingSettingsController < Spree::Admin::BaseController

  def edit
    @preferences_UPS = [:ups_login, :ups_password, :ups_key, :shipper_number]
    @preferences_FedEx = [:fedex_login, :fedex_password, :fedex_account, :fedex_key]
    @preferences_USPS = [:usps_login, :usps_commercial_base, :usps_commercial_plus]
    @preferences_CanadaPost = [:canada_post_login]
    @preferences_AustraliaPost = [:australia_post_login]
    @preferences_GeneralSettings = [:units, :unit_multiplier, :default_weight, :handling_fee,
      :max_weight_per_package, :test_mode]

    @config = Spree::ActiveShippingConfiguration.new
  end

  def update
    config = Spree::ActiveShippingConfiguration.new

    params.each do |name, value|
      next unless config.has_preference? name
      config[name] = value
    end

    redirect_to edit_admin_active_shipping_settings_path
  end

end

app/views/spree/admin/active_shipping_settings/edit.html.erb
<%= render partial: 'spree/admin/shared/sub_menu/configuration' %>

<% content_for :page_title do %>
  <%= Spree.t(:active_shipping_settings) %>
<% end %>

<%= form_tag admin_active_shipping_settings_path, method: :put  do |form| %>
  <div id="preferences" data-hook>
    <fieldset class="general no-border-top">
      <div class="row">
        <div class="col-md-6">
          <fieldset class="security no-border-bottom">
            <legend align="center"><%= Spree.t(:ups_settings)%></legend>
            <% @preferences_UPS.each do |key|
                type = @config.preference_type(key) %>
                <div class="field">
                  <%= label_tag(key, Spree.t(key) + ': ') + tag(:br) if type != :boolean %>
                  <%= preference_field_tag(key, @config[key], type: type) %>
                  <%= label_tag(key, Spree.t(key)) + tag(:br) if type == :boolean %>
                </div>
            <% end %>
          </fieldset>
        </div>
        <div class="col-md-6">
          <fieldset class="currency no-border-bottom">
            <legend align="center"><%= Spree.t(:fedex_settings)%></legend>
            <% @preferences_FedEx.each do |key|
                type = @config.preference_type(key) %>
                <div class="field">
                  <%= label_tag(key, Spree.t(key) + ': ') + tag(:br) if type != :boolean %>
                  <%= preference_field_tag(key, @config[key], type: type) %>
                  <%= label_tag(key, Spree.t(key)) + tag(:br) if type == :boolean %>
                </div>
            <% end %>
          </fieldset>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <fieldset class="security no-border-bottom">
            <legend align="center"><%= Spree.t(:usps_settings)%></legend>
            <% @preferences_USPS.each do |key|
                type = @config.preference_type(key) %>
                <div class="field">
                  <%= label_tag(key, Spree.t(key) + ': ') + tag(:br) if type != :boolean %>
                  <%= preference_field_tag(key, @config[key], type: type) %>
                  <%= label_tag(key, Spree.t(key)) + tag(:br) if type == :boolean %>
                </div>
            <% end %>
          </fieldset>
        </div>
        <div class="col-md-6">
          <fieldset class="currency no-border-bottom">
            <legend align="center"><%= Spree.t(:canada_post_settings)%></legend>
            <% @preferences_CanadaPost.each do |key|
                type = @config.preference_type(key) %>
                <div class="field">
                  <%= label_tag(key, Spree.t(key) + ': ') + tag(:br) if type != :boolean %>
                  <%= preference_field_tag(key, @config[key], type: type) %>
                  <%= label_tag(key, Spree.t(key)) + tag(:br) if type == :boolean %>
                </div>
            <% end %>
          </fieldset>
        </div>
        <div class="col-md-6">
          <fieldset class="currency no-border-bottom">
            <legend align="center"><%= Spree.t(:australia_post_settings)%></legend>
            <% @preferences_AustraliaPost.each do |key|
              type = @config.preference_type(key) %>
                <div class="field">
                  <%= label_tag(key, Spree.t(key) + ': ') + tag(:br) if type != :boolean %>
                  <%= preference_field_tag(key, @config[key], type: type) %>
                  <%= label_tag(key, Spree.t(key)) + tag(:br) if type == :boolean %>
                </div>
            <% end %>
          </fieldset>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <fieldset class="currency no-border-bottom">
            <legend align="center"><%= Spree.t(:general_settings)%></legend>
            <% @preferences_GeneralSettings.each do |key|
                type = @config.preference_type(key) %>
                <div class="field">
                  <%= label_tag(key, Spree.t(key) + ': ') + tag(:br) if type != :boolean %>
                  <%= preference_field_tag(key, @config[key], type: type) %>
                  <%= label_tag(key, Spree.t(key)) + tag(:br) if type == :boolean %>
                </div>
            <% end %>
          </fieldset>
        </div>
      </div>

      <%= render partial: 'spree/admin/shared/edit_resource_links', locals: { collection_url: edit_admin_active_shipping_settings_url } %>

    </fieldset>
  </div>
<% end %>